export * from './Stories/Stories';
export * from './MainProducts/MainProducts';
export * from './Promotions/Promotions';
export * from './About/About';
export * from './Banner/Banner';
export * from "./CatalogBlock/CatalogBlock";
export * from "./CatalogBlock/Card/CatalogBlockCard";
export * from "./Brands/Brands";
export * from "./ShippingPaymentInfo/ShippingPaymentInfo";
